[Settings]
  ID = "6f25da95-187c-4416-a36b-e5c83092fa73"

[Build]
  Publish = "dist/"
  Command = "make build"
  Functions = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://shortercat.netlify.com/*"
  to = "https:///shortercatechism.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://shortercat.netlify.com/*"
  to = "https:///shortercatechism.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://shortercatechism.app/*"
  to = "https:///shortercatechism.app/:splat"
  status = 301
  force = true
